### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by sanjayphp** [qbytesoft-com/QBAdminUi-Laravel-Boilerplate#1]
Dear Team,

Your template is nice to use. But i am facing a problem for using datatable. I have more than 10 rows in a database table. When i call it using "basicDataTable" id, default pagination does not showing. Please let me know how i have to fix it. I have included my blade file.

Thanks,
sanjay
[admin.blade.txt](https://github.com/qbytesoft-com/QBAdminUi-Laravel-Boilerplate/files/4629179/admin.blade.txt)
[index.blade.txt](https://github.com/qbytesoft-com/QBAdminUi-Laravel-Boilerplate/files/4629191/index.blade.txt)

**Comment by morshadunnur** [comment]
Can you give me the screenshot of the broken design after integrating datatables?

**Comment by morshadunnur** [comment]
> Dear Team,
> 
> Your template is nice to use. But i am facing a problem for using datatable. I have more than 10 rows in a database table. When i call it using "basicDataTable" id, default pagination does not showing. Please let me know how i have to fix it. I have included my blade file.
> 
> Thanks,
> sanjay
> [admin.blade.txt](https://github.com/qbytesoft-com/QBAdminUi-Laravel-Boilerplate/files/4629179/admin.blade.txt)
> [index.blade.txt](https://github.com/qbytesoft-com/QBAdminUi-Laravel-Boilerplate/files/4629191/index.blade.txt)

Here, I have changed folder name in public/qbadminui/js directory. And Please check our html template there by default pagination is hidden. You need to enable from dataTable Js file where you initial the table id. So, you can follow the dataTable documentation to enable pagination. 
Thanks

**Comment by mrmarufpro** [comment]
![Annotation 2020-05-14 230224](https://user-images.githubusercontent.com/39343312/82010384-bf2d5700-9693-11ea-9c85-820cfda948c8.png)

 Check the files directory on your local machine and follow the file directory name correctly. In your case, I think you made a little mistake on the script linking.

Thanks

**Comment by sanjayphp** [comment]
Dear Team,
Thanks for your quick response. I have enabled pagination. My table id is "basicDataTable". Please check my attached dataTable_script.js file which i have received and customized a little bit. Please let me know what I am doing wrong.
[dataTable_script.txt](https://github.com/qbytesoft-com/QBAdminUi-Laravel-Boilerplate/files/4632175/dataTable_script.txt)


Thanks
sanjay

**Comment by sanjayphp** [comment]
Yes, I already renamed directory which had space. If you check admin.blade file which i sent yesterday, you will get that.

**Comment by mrmarufpro** [comment]
I have checked our code, there is no problem with datatable I hope.

Please follow this step:

1. Make sure your page loads this 3 scripts (`jquery-3.3.1.min.js`, `datatables.min.js` and `dataTable_script.js`) properly by using the browsers `view page source` option.
2. At the source page click on the script link and check is it available on that page or not.
3. Take a look at the browser console, if there is an error base on datatable then tell us.

**Comment by sanjayphp** [comment]
Dear Team, I have solved the issue.  There was no thead propery in my table, that's why it did not work. Anyway, thanks for your tremendous support.
