### ISSUE TITLE
Left Sidebar child menu closed down

### ISSUE THREAD

**Issue by sanjayphp** [qbytesoft-com/QBAdminUi-Laravel-Boilerplate#2]
Dear Team,

When I click a child menu from left sidebar, it is closed down. It should be active after click also. Please check .

Thanks
sanjay

**Comment by mrmarufpro** [comment]
Hei Sanjay.

Are you talking about the side menu ( Basic UI elements, Form elements, Charts, etc)?
After you click the menu and immediately click the other menu, the previous menu will be closed.
If so,
I want to let you know that this is the default system of bootstrap 4 Accordion components.
[Accordion ](https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example) - Bootstrap 4 Accordion 

If you don't want this option then follow these steps:

1. On the accordion div find the `data-parent="#accordion"`  attribute
2. Remove the attribute

I hope you'll get it.

Thank you
Maruf

**Comment by sanjayphp** [comment]
Thanks for response.

Lets say, I just click "Alert" submenu under "Basic Elements" menu. Alert page is opened but "Alert" submenu is not showing active. It returns back to "Basic Elements" menu. I think "Alert" menu should be active when alert page is opened in window.

Please let me know.
Thanks,
sanjay

**Comment by Maruf-Ahmed76** [comment]
Hey Sanjay,
Thanks for your suggestion.
I'll make it happened on my next commit.

**Comment by Maruf-Ahmed76** [comment]
Hey Sanjay
Thanks for your suggestion. I'll make it happened soon.

**Comment by mrmarufpro** [comment]
Hey Sanjay
Thanks for your suggestion. We'll make it happened soon.

**Comment by morshadunnur** [comment]
Hey @sanjayphp pull the latest . Hope everything is alright.
Thanks for your feedback 👍

**Comment by sanjayphp** [comment]
Thanks for fixed the issue. But if you can just tell me which files you have modified ,it would be better for me. Let me know.
